name: crcrme_banque_stages
description: An application that helps teachers manage their students.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none"

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
    sdk: ">=2.17.5 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
    provider: ^6.0.3
    flutter_spinbox: ^0.9.0
    autocomplete_textfield: ^2.0.1
    flutter_rating_bar: ^4.0.1
    image_picker: ^0.8.5+3
    firebase_core: ^1.20.0
    firebase_auth: ^3.6.2
    firebase_storage: ^10.3.4
    firebase_database: ^9.1.0
    path: ^1.8.1
    nanoid: ^1.0.0
    collection: ^1.16.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
    uses-material-design: true

    assets:
        - assets/jobs-data.json
        - assets/questions.json
